"""Fixed ambiguous foreign keys for appointments

Revision ID: 9977bcb8c708
Revises: fa5df99767fc
Create Date: 2025-06-04 21:33:30.560794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9977bcb8c708'
down_revision: Union[str, None] = 'fa5df99767fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
