"""Add new fields to appointments

Revision ID: c96ea19261c7
Revises: e5bfea0c460c
Create Date: 2025-05-28 22:47:30.490793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96ea19261c7'
down_revision: Union[str, None] = 'e5bfea0c460c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('client_phone', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('status', sa.Enum('completed', 'not_completed', name='appointmentstatus'), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'client', 'master', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'client', 'master', name='userrole'),
               nullable=True)
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'client_phone')
    op.drop_column('appointments', 'client_name')
    # ### end Alembic commands ###
