"""Добавлено поле duration для услуги

Revision ID: d268aac29af2
Revises: 9977bcb8c708
Create Date: 2025-06-09 11:41:01.641444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd268aac29af2'
down_revision: Union[str, None] = '9977bcb8c708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('services', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration')
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
