"""Added comment and master to Appointment

Revision ID: fa5df99767fc
Revises: c96ea19261c7
Create Date: 2025-06-04 21:10:59.687093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5df99767fc'
down_revision: Union[str, None] = 'c96ea19261c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('master_id', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'appointments', 'users', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('appointments', 'master_id')
    op.drop_column('appointments', 'comment')
    # ### end Alembic commands ###
